Update types.md
rizinorg/book pull request #109
Opened 2023-11-22 00:03 UTC by chucklesb

Fixed quotation syntax around `td` commands. Replaced references to `tl` command with `avga` command. Updated outputs of commands to reflect current behavior. Cleaned up some verbiage.

2023-11-22 00:08 UTC, chucklesb commented on src/analysis/types.md
>  ## Internal representation
Is any of the below information still valid?

2023-11-22 00:11 UTC, chucklesb commented on src/analysis/types.md
>  ## Internal representation
Additionally, this document states that the typedefs are stored in Sdb, but I'm not sure if that's still the case.

2023-11-22 13:01 UTC, XVilka requested changes
.

2023-11-22 22:43 UTC, chucklesb commented on src/analysis/types.md
>  ## Internal representation
Ok, I have removed the "Internal Representation" section and mention of type definitions being stored in Sdb. Also small formatting and verbiage changes.

2023-11-23 00:33 UTC, wargio approved these changes
LGTM

2023-11-28 10:05 UTC, XVilka approved these changes

2023-11-28 10:06 UTC, merged