updated rizin.md
rizinorg/book pull request #57
Opened 2021-05-27 06:35 UTC by h4x5p4c3

1. removed cheatsheet by pwntester.
2. removed rizin wike which isn't actually present 
3. changed `https://rizin.today` to `https://rizin.re/posts/`

2021-05-27 06:35 UTC, h4x5p4c3 commented
*rizin wiki

2021-05-27 06:53 UTC, officialcjunior commented
Great, thanks.
I think, the first paragraph of the page can also be removed/tweaked, since the author could not have used Rizin in 2011.

2021-05-27 06:57 UTC, h4x5p4c3 commented
welcome, ill remove it then

2021-05-27 09:46 UTC, wargio requested changes

2021-05-27 09:46 UTC, wargio commented on src/crackmes/avatao/01-reverse4/rizin.md
>  - [Rizin Book](https://www.gitbook.com/book/rizinorg/rizinbook/details)
point this to `book.rizin.re`
```suggestion
- [Rizin Book](https://book.rizin.re)
```

2021-05-28 08:32 UTC, wargio approved these changes

2021-05-28 11:13 UTC, XVilka approved these changes

2021-05-28 11:13 UTC, merged