remove Makefile on dev-asm
rizinorg/book pull request #98
Opened 2023-06-19 11:20 UTC by gogo2464

Fixes https://github.com/rizinorg/book/issues/97

Focuses on asm plugin only. Does not document meson on other plugins.

2023-06-19 15:19 UTC, gogo2464 commented on src/plugins/dev-asm.md
> -OBJS=$(NAME).o
I belived it has been removed in favor of meson.

2023-06-19 16:28 UTC, XVilka requested changes

2023-06-19 16:28 UTC, XVilka commented on src/plugins/dev-asm.md
> -OBJS=$(NAME).o
Instead of just removing it's better to provide the example of the Meson file

2023-06-19 17:05 UTC, wargio commented on src/plugins/dev-asm.md
> -OBJS=$(NAME).o
> the makefile has been removed

This is a misconception! the book entry is about making an asm plugin for rizin, and to build the plugin you can use a Makefile. I do agree we have removed them from rizin itself in favor of meson, but is not strictly required to use meson also for the external plugins.

That said, i strongly agree with xvilka to have this replaced with a `meson.build` example is more beneficial.

2023-06-19 17:11 UTC, gogo2464 commented on src/plugins/dev-asm.md
> -OBJS=$(NAME).o
I have already a branch of rizin with asm plugin with meson. I can update the documentation for meson.

Should I remove Makefile doc and replace it with meson or just add meson? Two way might be confusing.

2023-06-20 00:34 UTC, wargio commented on src/plugins/dev-asm.md
> -OBJS=$(NAME).o
remove the makefile and add the meson example.

2023-06-20 09:20 UTC, gogo2464 commented on src/plugins/dev-asm.md
> -OBJS=$(NAME).o
Perfect! I know what I should do. I should be able to fix it this week.

Sorry for the time I made you waste in this misundertsanding.

2023-06-20 14:32 UTC, wargio commented on src/plugins/dev-asm.md
> -OBJS=$(NAME).o
doesn't matter. better wasting some time and have a good PR.

2023-06-21 03:05 UTC, wargio commented on src/plugins/dev-asm.md
> ++  ''arch/mycpu/mycpu_disas.c,
this is wrong.
```suggestion
+  'arch/mycpu/mycpu_disas.c',
```

2023-06-21 09:26 UTC, gogo2464 commented
Seems good for me.

Sadly I have not really compiled the mycpu plugin really.
Hopefully I have created my own plugin to handle evm: https://github.com/rizinorg/rizin/pull/3595 so I can see.

2023-06-21 14:34 UTC, wargio commented
can you add to the example the meson template?

2023-06-21 16:06 UTC, gogo2464 commented
I believed I have already done https://github.com/rizinorg/book/pull/98/files#diff-cc0314ce2a2ce993dd86f5b416f5ece4ad633a55911c53f41c1b23a6ae688b16R89

2023-06-21 17:33 UTC, gogo2464 commented
@wargio Did I forgot something?

2023-06-22 02:46 UTC, wargio approved these changes
Sorry, i misread it yesterday.

2023-06-22 13:03 UTC, gogo2464 commented
Seems ready to merge @XVilka  ?

2023-06-22 13:43 UTC, XVilka requested changes
You added how to add it to a Rizin tree, but please also add a standalone Meson file, like it was done with Makefile before. You can see examples from rizin-extras how it can be done.

2023-06-22 17:49 UTC, gogo2464 commented
@XVilka is it better now?

2023-06-22 17:53 UTC, XVilka requested changes
No, what I meant, is you just need a meson file for just one particular plugin, just like this: https://github.com/rizinorg/rizin-extras/blob/master/jaguar-gpu/meson.build

2023-06-22 18:21 UTC, gogo2464 commented
I am confused... like this?

2023-06-23 01:38 UTC, wargio approved these changes

2023-06-23 02:42 UTC, XVilka approved these changes

2023-06-23 02:42 UTC, merged

2023-06-23 13:16 UTC, gogo2464 commented
@wargio @XVilka Does it pass GH-PAGES? I got a warning by email. :-/